#!/usr/bin/env python3
"""
Agentic Task Handler
Handles tasks with guidelines enforcement, test generation, and documentation
"""
import json
import subprocess
import os
from typing import Dict, Any

class AgenticHandler:
    def __init__(self):
        self.test_generators = {
            'python': self.generate_python_tests,
            'javascript': self.generate_js_tests,
            'java': self.generate_java_tests,
            'kotlin': self.generate_kotlin_tests
        }
        
        self.doc_generators = {
            'python': self.generate_python_docs,
            'javascript': self.generate_js_docs,
            'java': self.generate_java_docs,
            'kotlin': self.generate_kotlin_docs
        }
    
    def handle_agentic_task(self, task: Dict[str, Any]) -> Dict[str, Any]:
        """
        Handle an agentic task with guidelines, tests, and docs
        """
        result = {
            'success': False,
            'output': None,
            'tests_generated': False,
            'docs_generated': False,
            'guidelines_followed': False,
            'errors': []
        }
        
        try:
            # Extract agentic metadata
            guidelines = task.get('guidelines', {})
            test_reqs = task.get('testRequirements', {})
            doc_template = task.get('documentationTemplate', {})
            metadata = task.get('agenticMetadata', {})
            
            # Execute the main task with guidelines
            main_result = self.execute_with_guidelines(task, guidelines)
            result['output'] = main_result
            result['guidelines_followed'] = True
            
            # Generate tests if required
            if metadata.get('autoGenerateTests', False):
                tests_result = self.generate_tests(task, test_reqs)
                result['tests_generated'] = tests_result['success']
                result['tests'] = tests_result.get('tests', [])
                if not tests_result['success']:
                    result['errors'].append(f"Test generation: {tests_result.get('error')}")
            
            # Generate documentation if required
            if metadata.get('autoGenerateDocs', False):
                docs_result = self.generate_documentation(task, doc_template)
                result['docs_generated'] = docs_result['success']
                result['documentation'] = docs_result.get('docs', '')
                if not docs_result['success']:
                    result['errors'].append(f"Doc generation: {docs_result.get('error')}")
            
            result['success'] = True
            
        except Exception as e:
            result['errors'].append(f"Agentic handler error: {str(e)}")
        
        return result
    
    def execute_with_guidelines(self, task: Dict[str, Any], guidelines: Dict[str, Any]) -> str:
        """
        Execute task with project guidelines enforced
        """
        # Build enhanced prompt with guidelines
        enhanced_task = self.build_enhanced_prompt(task, guidelines)
        
        # Execute via Kiro with enhanced prompt
        result = subprocess.run(
            ['kiro', 'execute', enhanced_task],
            capture_output=True,
            text=True,
            timeout=300
        )
        
        return result.stdout if result.returncode == 0 else result.stderr
    
    def build_enhanced_prompt(self, task: Dict[str, Any], guidelines: Dict[str, Any]) -> str:
        """
        Build enhanced prompt with guidelines
        """
        prompt_parts = [
            f"Project: {task['project']}",
            f"Task: {task['task']}",
            "",
            "Guidelines to follow:",
            f"- Language/Framework: {guidelines.get('language', 'N/A')}",
            f"- Style Guide: {guidelines.get('style', 'N/A')}",
            f"- Testing Framework: {guidelines.get('testing', 'N/A')}",
            f"- Documentation: {guidelines.get('documentation', 'N/A')}",
            "",
            "Design Patterns to use:",
        ]
        
        for pattern in guidelines.get('patterns', []):
            prompt_parts.append(f"- {pattern}")
        
        prompt_parts.extend([
            "",
            "Security requirements:",
        ])
        
        for req in guidelines.get('security', []):
            prompt_parts.append(f"- {req}")
        
        prompt_parts.extend([
            "",
            "Performance considerations:",
        ])
        
        for perf in guidelines.get('performance', []):
            prompt_parts.append(f"- {perf}")
        
        return "\n".join(prompt_parts)
    
    def generate_tests(self, task: Dict[str, Any], test_reqs: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate tests based on requirements
        """
        try:
            language = self.detect_language(task)
            generator = self.test_generators.get(language)
            
            if not generator:
                return {'success': False, 'error': f'No test generator for {language}'}
            
            tests = generator(task, test_reqs)
            
            return {
                'success': True,
                'tests': tests
            }
        
        except Exception as e:
            return {'success': False, 'error': str(e)}
    
    def generate_documentation(self, task: Dict[str, Any], doc_template: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate documentation based on template
        """
        try:
            language = self.detect_language(task)
            generator = self.doc_generators.get(language)
            
            if not generator:
                return {'success': False, 'error': f'No doc generator for {language}'}
            
            docs = generator(task, doc_template)
            
            return {
                'success': True,
                'docs': docs
            }
        
        except Exception as e:
            return {'success': False, 'error': str(e)}
    
    def detect_language(self, task: Dict[str, Any]) -> str:
        """
        Detect programming language from project
        """
        project = task['project']
        
        language_map = {
            'diaperstops': 'java',
            'reno-app': 'javascript',
            'climate': 'python',
            'translator': 'python',
            'android': 'kotlin'
        }
        
        return language_map.get(project, 'python')
    
    # Test generators
    def generate_python_tests(self, task: Dict[str, Any], test_reqs: Dict[str, Any]) -> list:
        """Generate Python tests using pytest"""
        tests = []
        
        # Unit test template
        unit_test = f"""
import pytest
from {task['project']} import *

class Test{task['project'].title()}:
    '''
    Test suite for {task['project']}
    Coverage target: {test_reqs.get('unitTests', {}).get('coverage', 80)}%
    '''
    
    def test_basic_functionality(self):
        '''Test basic functionality'''
        # Arrange
        # TODO: Setup test data
        
        # Act
        # TODO: Execute function
        
        # Assert
        # TODO: Verify results
        assert True
    
    def test_edge_cases(self):
        '''Test edge cases'''
        # Test null/undefined
        # Test empty values
        # Test boundary conditions
        pass
    
    def test_error_scenarios(self):
        '''Test error handling'''
        with pytest.raises(Exception):
            # TODO: Test error scenarios
            pass
"""
        tests.append({
            'type': 'unit',
            'framework': 'pytest',
            'code': unit_test
        })
        
        return tests
    
    def generate_js_tests(self, task: Dict[str, Any], test_reqs: Dict[str, Any]) -> list:
        """Generate JavaScript tests using Jest"""
        tests = []
        
        # Unit test template
        unit_test = f"""
describe('{task['project']}', () => {{
  // Coverage target: {test_reqs.get('unitTests', {}).get('coverage', 80)}%
  
  test('should handle basic functionality', () => {{
    // Arrange
    // TODO: Setup test data
    
    // Act
    // TODO: Execute function
    
    // Assert
    // TODO: Verify results
    expect(true).toBe(true);
  }});
  
  test('should handle edge cases', () => {{
    // Test null/undefined
    // Test empty values
    // Test boundary conditions
  }});
  
  test('should handle errors', () => {{
    // TODO: Test error scenarios
    expect(() => {{
      // Error-inducing code
    }}).toThrow();
  }});
}});
"""
        tests.append({
            'type': 'unit',
            'framework': 'jest',
            'code': unit_test
        })
        
        return tests
    
    def generate_java_tests(self, task: Dict[str, Any], test_reqs: Dict[str, Any]) -> list:
        """Generate Java tests using JUnit"""
        tests = []
        
        # Unit test template
        unit_test = f"""
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Test suite for {task['project']}
 * Coverage target: {test_reqs.get('unitTests', {}).get('coverage', 80)}%
 */
class {task['project'].title()}Test {{
    
    @Test
    void shouldHandleBasicFunctionality() {{
        // Arrange
        // TODO: Setup test data
        
        // Act
        // TODO: Execute method
        
        // Assert
        // TODO: Verify results
        assertTrue(true);
    }}
    
    @Test
    void shouldHandleEdgeCases() {{
        // Test null values
        // Test empty values
        // Test boundary conditions
    }}
    
    @Test
    void shouldHandleErrors() {{
        // TODO: Test error scenarios
        assertThrows(Exception.class, () -> {{
            // Error-inducing code
        }});
    }}
}}
"""
        tests.append({
            'type': 'unit',
            'framework': 'junit5',
            'code': unit_test
        })
        
        return tests
    
    def generate_kotlin_tests(self, task: Dict[str, Any], test_reqs: Dict[str, Any]) -> list:
        """Generate Kotlin tests using JUnit"""
        tests = []
        
        # Unit test template
        unit_test = f"""
import org.junit.Test
import org.junit.Assert.*

/**
 * Test suite for {task['project']}
 * Coverage target: {test_reqs.get('unitTests', {}).get('coverage', 80)}%
 */
class {task['project'].title()}Test {{
    
    @Test
    fun `should handle basic functionality`() {{
        // Arrange
        // TODO: Setup test data
        
        // Act
        // TODO: Execute function
        
        // Assert
        // TODO: Verify results
        assertTrue(true)
    }}
    
    @Test
    fun `should handle edge cases`() {{
        // Test null values
        // Test empty values
        // Test boundary conditions
    }}
    
    @Test(expected = Exception::class)
    fun `should handle errors`() {{
        // TODO: Test error scenarios
    }}
}}
"""
        tests.append({
            'type': 'unit',
            'framework': 'junit',
            'code': unit_test
        })
        
        return tests
    
    # Documentation generators
    def generate_python_docs(self, task: Dict[str, Any], doc_template: Dict[str, Any]) -> str:
        """Generate Python documentation"""
        return f"""
\"\"\"
{doc_template.get('fileHeader', {}).get('description', 'Module description')}

Author: {doc_template.get('fileHeader', {}).get('author', 'Auto-generated')}
Date: {doc_template.get('fileHeader', {}).get('date', '')}
Project: {task['project']}
\"\"\"

# TODO: Add module-level documentation
# TODO: Document all functions with docstrings
# TODO: Include usage examples
"""
    
    def generate_js_docs(self, task: Dict[str, Any], doc_template: Dict[str, Any]) -> str:
        """Generate JavaScript documentation"""
        return f"""
/**
 * {doc_template.get('fileHeader', {}).get('description', 'Module description')}
 * 
 * @author {doc_template.get('fileHeader', {}).get('author', 'Auto-generated')}
 * @date {doc_template.get('fileHeader', {}).get('date', '')}
 * @project {task['project']}
 */

// TODO: Add JSDoc comments for all functions
// TODO: Document parameters and return types
// TODO: Include usage examples
"""
    
    def generate_java_docs(self, task: Dict[str, Any], doc_template: Dict[str, Any]) -> str:
        """Generate Java documentation"""
        return f"""
/**
 * {doc_template.get('fileHeader', {}).get('description', 'Class description')}
 * 
 * @author {doc_template.get('fileHeader', {}).get('author', 'Auto-generated')}
 * @version 1.0
 * @since {doc_template.get('fileHeader', {}).get('date', '')}
 */

// TODO: Add JavaDoc for all public methods
// TODO: Document parameters with @param
// TODO: Document return values with @return
// TODO: Document exceptions with @throws
"""
    
    def generate_kotlin_docs(self, task: Dict[str, Any], doc_template: Dict[str, Any]) -> str:
        """Generate Kotlin documentation"""
        return f"""
/**
 * {doc_template.get('fileHeader', {}).get('description', 'Class description')}
 * 
 * @author {doc_template.get('fileHeader', {}).get('author', 'Auto-generated')}
 * @since {doc_template.get('fileHeader', {}).get('date', '')}
 */

// TODO: Add KDoc for all public functions
// TODO: Document parameters with @param
// TODO: Document return values with @return
// TODO: Include usage examples with @sample
"""
