// Agentic Queue System
// Specialized queues for different types of agentic work

class AgenticQueue {
  constructor() {
    // Specialized queues by type
    this.queues = {
      'code-generation': [],
      'code-review': [],
      'testing': [],
      'documentation': [],
      'refactoring': [],
      'debugging': [],
      'deployment': [],
      'monitoring': []
    };
    
    // Guidelines per project
    this.projectGuidelines = new Map();
    
    // Test requirements per project
    this.testRequirements = new Map();
    
    // Documentation templates
    this.docTemplates = new Map();
  }
  
  // Add task to appropriate queue based on type
  enqueue(task) {
    const queueType = this.determineQueueType(task);
    
    // Enrich task with guidelines
    const enrichedTask = this.enrichWithGuidelines(task);
    
    // Add to queue
    this.queues[queueType].push(enrichedTask);
    
    return {
      queueType,
      position: this.queues[queueType].length,
      enrichedTask
    };
  }
  
  // Determine which queue based on task content
  determineQueueType(task) {
    const taskLower = task.task.toLowerCase();
    
    // Code generation keywords
    if (taskLower.match(/create|build|implement|add feature|new component/)) {
      return 'code-generation';
    }
    
    // Code review keywords
    if (taskLower.match(/review|check|validate|audit|inspect/)) {
      return 'code-review';
    }
    
    // Testing keywords
    if (taskLower.match(/test|unit test|integration test|e2e|coverage/)) {
      return 'testing';
    }
    
    // Documentation keywords
    if (taskLower.match(/document|readme|api docs|comment|explain/)) {
      return 'documentation';
    }
    
    // Refactoring keywords
    if (taskLower.match(/refactor|optimize|improve|clean up|restructure/)) {
      return 'refactoring';
    }
    
    // Debugging keywords
    if (taskLower.match(/fix|bug|error|debug|issue|problem/)) {
      return 'debugging';
    }
    
    // Deployment keywords
    if (taskLower.match(/deploy|release|publish|ship/)) {
      return 'deployment';
    }
    
    // Monitoring keywords
    if (taskLower.match(/monitor|alert|log|track|observe/)) {
      return 'monitoring';
    }
    
    // Default to code-generation
    return 'code-generation';
  }
  
  // Enrich task with project-specific guidelines
  enrichWithGuidelines(task) {
    const guidelines = this.projectGuidelines.get(task.project) || this.getDefaultGuidelines(task.project);
    const testReqs = this.testRequirements.get(task.project) || this.getDefaultTestRequirements(task.project);
    const docTemplate = this.docTemplates.get(task.project) || this.getDefaultDocTemplate(task.project);
    
    return {
      ...task,
      guidelines,
      testRequirements: testReqs,
      documentationTemplate: docTemplate,
      agenticMetadata: {
        requiresTests: true,
        requiresDocs: true,
        requiresReview: task.priority === 'high' || task.priority === 'urgent',
        autoGenerateTests: true,
        autoGenerateDocs: true
      }
    };
  }
  
  // Default guidelines per project
  getDefaultGuidelines(project) {
    const guidelines = {
      'diaperstops': {
        language: 'Java/Spring Boot + React',
        style: 'Google Java Style Guide',
        testing: 'JUnit 5 + React Testing Library',
        documentation: 'JavaDoc + JSDoc',
        patterns: ['MVC', 'Repository Pattern', 'Service Layer'],
        security: ['Input validation', 'SQL injection prevention', 'XSS protection'],
        performance: ['Lazy loading', 'Caching', 'Database indexing']
      },
      'reno-app': {
        language: 'React Native + Node.js',
        style: 'Airbnb JavaScript Style Guide',
        testing: 'Jest + React Native Testing Library',
        documentation: 'JSDoc + README',
        patterns: ['Component composition', 'Custom hooks', 'Context API'],
        security: ['API authentication', 'Secure storage', 'HTTPS only'],
        performance: ['Memoization', 'Lazy loading', 'Image optimization']
      },
      'climate': {
        language: 'Python + React',
        style: 'PEP 8 + Airbnb',
        testing: 'pytest + Jest',
        documentation: 'Sphinx + JSDoc',
        patterns: ['Clean Architecture', 'Dependency Injection', 'Factory Pattern'],
        security: ['Input sanitization', 'API rate limiting', 'Data encryption'],
        performance: ['Async operations', 'Caching', 'CDN usage']
      },
      'translator': {
        language: 'Python',
        style: 'PEP 8',
        testing: 'pytest',
        documentation: 'Sphinx',
        patterns: ['Strategy Pattern', 'Adapter Pattern'],
        security: ['API key management', 'Rate limiting'],
        performance: ['Batch processing', 'Caching translations']
      },
      'android': {
        language: 'Kotlin + Jetpack Compose',
        style: 'Kotlin Coding Conventions',
        testing: 'JUnit + Espresso',
        documentation: 'KDoc',
        patterns: ['MVVM', 'Repository Pattern', 'Use Cases'],
        security: ['ProGuard', 'Certificate pinning', 'Encrypted storage'],
        performance: ['Coroutines', 'Flow', 'Lazy initialization']
      }
    };
    
    return guidelines[project] || {
      language: 'Unknown',
      style: 'Standard conventions',
      testing: 'Unit tests required',
      documentation: 'README + inline comments',
      patterns: ['SOLID principles'],
      security: ['Input validation', 'Authentication'],
      performance: ['Optimization as needed']
    };
  }
  
  // Default test requirements
  getDefaultTestRequirements(project) {
    return {
      unitTests: {
        required: true,
        coverage: 80,
        framework: this.getDefaultGuidelines(project).testing.split('+')[0].trim()
      },
      integrationTests: {
        required: project === 'diaperstops' || project === 'reno-app',
        coverage: 60,
        framework: this.getDefaultGuidelines(project).testing.split('+')[1]?.trim() || 'Integration tests'
      },
      e2eTests: {
        required: project === 'diaperstops',
        coverage: 40,
        framework: 'Cypress'
      },
      testStructure: {
        arrange: 'Setup test data and mocks',
        act: 'Execute the function/method',
        assert: 'Verify expected outcomes'
      },
      testNaming: 'should_ExpectedBehavior_When_StateUnderTest',
      mockingStrategy: 'Mock external dependencies',
      edgeCases: ['null/undefined', 'empty values', 'boundary conditions', 'error scenarios']
    };
  }
  
  // Default documentation template
  getDefaultDocTemplate(project) {
    return {
      fileHeader: {
        description: 'Brief description of file purpose',
        author: 'Auto-generated by Agentic System',
        date: new Date().toISOString().split('T')[0],
        project: project
      },
      functionDoc: {
        description: 'What the function does',
        parameters: 'List all parameters with types and descriptions',
        returns: 'Return type and description',
        throws: 'Exceptions that may be thrown',
        examples: 'Usage examples'
      },
      classDoc: {
        description: 'Class purpose and responsibility',
        properties: 'List all properties',
        methods: 'List all public methods',
        usage: 'How to instantiate and use'
      },
      apiDoc: {
        endpoint: 'API endpoint path',
        method: 'HTTP method',
        description: 'What the endpoint does',
        parameters: 'Query/path/body parameters',
        responses: 'Success and error responses',
        examples: 'Request/response examples'
      }
    };
  }
  
  // Get next task from queue
  dequeue(queueType) {
    if (!this.queues[queueType] || this.queues[queueType].length === 0) {
      return null;
    }
    
    return this.queues[queueType].shift();
  }
  
  // Get queue stats
  getStats() {
    const stats = {};
    
    for (const [queueType, queue] of Object.entries(this.queues)) {
      stats[queueType] = {
        pending: queue.length,
        tasks: queue.map(t => ({
          id: t.id,
          project: t.project,
          priority: t.priority
        }))
      };
    }
    
    return stats;
  }
  
  // Set custom guidelines for a project
  setProjectGuidelines(project, guidelines) {
    this.projectGuidelines.set(project, guidelines);
  }
  
  // Set custom test requirements
  setTestRequirements(project, requirements) {
    this.testRequirements.set(project, requirements);
  }
  
  // Set custom doc template
  setDocTemplate(project, template) {
    this.docTemplates.set(project, template);
  }
}

module.exports = AgenticQueue;
